#!/bin/sh
#
# List or retrieve .gitignore templates using GitHub API (http://developer.github.com/v3/gitignore/)
# Note: v3 API has a limit of 60 requests per hour for unauthenticated users.
#

if [ -z "$1" ]; then
    curl -s https://api.github.com/gitignore/templates |
    sed -ne 's/\s*"\(.*\)".*$/\1/p'
else 
    curl -s https://api.github.com/gitignore/templates/$1 |
    sed -ne '/"source":/ { s/.*"source":.*"\(.*\)".*$/\1/; s/\\n/\n/g; p }'
fi

exit
