#!/bin/sh
#
# Download and install the latest version of io.js (to $HOME/bin)
#

set -e

uname -m | grep "64" >/dev/null 2>&1 &&
iojs_arch="x64" ||
iojs_arch="x86"

iojs_os="`uname -s | tr '[:upper:]' '[:lower:]'`"

iojs_version="`curl -sL https://iojs.org/dist/index.tab | head -2 |
sed -ne 's@\(v[0-9]*\.[0-9]*\.[0-9]*\).*@\1@p'`"

iojs_binary="https://iojs.org/dist/$iojs_version/iojs-$iojs_version-$iojs_os-$iojs_arch.tar.gz"

if [ "$1" = "-s" ]; then
    echo "Latest version is $iojs_binary"
    exit 0
fi

echo "Downloading $iojs_binary..."
curl -sL "$iojs_binary" | tar xvzf -

iojs_path="`pwd`/`basename $iojs_binary .tar.gz`"

# create symlinks $HOME/bin/{node,iojs,npm}
[ -d ~/bin ] || mkdir ~/bin
ln -sfv "$iojs_path/bin/node" "$HOME/bin/node"
ln -sfv "$iojs_path/bin/node" "$HOME/bin/iojs"
ln -sfv "$iojs_path/bin/npm" "$HOME/bin/npm"

exit
