#!/bin/sh
#
# Download and install the latest version of node.js (to $HOME/bin)
# (w) <github.com/ivanra>
#

set -e

version_only=0
make_symlinks=0

while true; do
    case "$1" in
        -s)
            version_only=1
            shift ;;
        -l)
            make_symlinks=1
            shift ;;
        *)
            break ;;
    esac
done

uname -m | grep "64" >/dev/null 2>&1 &&
node_arch="x64" ||
node_arch="x86"

node_os="`uname -s | tr '[:upper:]' '[:lower:]'`"

node_latest_repo="http://nodejs.org/dist/latest"
node_binary="`curl -sL $node_latest_repo |
sed -ne 's@.*href=\"\(node-.*-'$node_os'-'$node_arch'.tar.xz\)\".*@\1@p'`"

if [ $version_only = 1 ]; then
    echo "Latest version is $node_binary"
    exit 0
fi

echo "Downloading $node_binary..."
curl -sL "$node_latest_repo/$node_binary" | tar xvJf -

if [ $make_symlinks = 1 ]; then
    node_path="`pwd`/`basename $node_binary .tar.xz`"
    # create symlinks $HOME/bin/{node,npm}
    [ -d ~/bin ] || mkdir ~/bin
    ln -sfv "$node_path/bin/node" "$HOME/bin/node"
    ln -sfv "$node_path/bin/npm" "$HOME/bin/npm"
fi

exit
